# This is a basic workflow to help you get started with Actions

name: Create IAM roles and policies

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: '3.6'
      # Runs a set of commands using the runners shell
      - name: Configure AWS credentials from Production account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      # Role creation usng AWS CLI
      - name: create iam role with trust policy
        run: |
          aws iam create-role --role-name Test-Role --assume-role-policy-document file://trust-policy.json 
      
      - name: attach user manager policy
        run: |
          aws iam put-role-policy --role-name Test-Role --policy-name ExamplePolicy --policy-document file://my-policy.json
      
      - name: attach AWS policy to role
        run: |
          aws iam attach-role-policy --policy-arn arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess --role-name Test-Role
      - name: attach AWS policy to role
        run: |
          aws iam attach-role-policy --policy-arn arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess --role-name Test-Role
      - name: Get Role ARN
        run: |
          aws iam get-role --role-name Test-Role  
